services:
  nodeapp:
    build: .
    container_name: nodeapp
    ports:
      - "3000:3000"
    depends_on:
      - mongodb


  mongodb:
    image: mongo:7
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
